//
// Created by cluster on 22-11-9.
//

#ifndef MUTECT2CPP_MASTER_ERRORTYPE_H
#define MUTECT2CPP_MASTER_ERRORTYPE_H
enum ErrorType {
    ARTIFACT, NON_SOMATIC, SEQUENCING
};

#endif //MUTECT2CPP_MASTER_ERRORTYPE_H

