//
// Created by 梦想家xixi on 2021/12/24.
//

#ifndef MUTECT2CPP_MASTER_CLIPPINGREPRESENTATION_H
#define MUTECT2CPP_MASTER_CLIPPINGREPRESENTATION_H


enum ClippingRepresentation{
    WRITE_NS,
    WRITE_Q0S,
    WRITE_NS_Q0S,
    SOFTCLIP_BASES,
    HARDCLIP_BASES,
    REVERT_SOFTCLIPPED_BASES,
    NULL_ClippingRepresentation
};


#endif //MUTECT2CPP_MASTER_CLIPPINGREPRESENTATION_H
